2024-03-11:23:54:58,180 INFO     [fetch.py:121] Currently Fetching https://codeforces.com/contest/1941/submission/250648064 ...
2024-03-11:23:55:30,062 INFO     [fetch.py:81] Currently Fetching https://codeforces.com/contest/1941/submission/250812385 ...
2024-03-11:23:55:33,564 INFO     [hack.py:25] Trying to hack submission 250812385 ...
2024-03-11:23:55:37,341 INFO     [fetch.py:81] Currently Fetching https://codeforces.com/contest/1941/submission/250812337 ...
2024-03-11:23:55:43,991 INFO     [hack.py:25] Trying to hack submission 250812337 ...
2024-03-11:23:55:46,055 INFO     [fetch.py:81] Currently Fetching https://codeforces.com/contest/1941/submission/250812313 ...
2024-03-11:23:55:46,701 INFO     [hack.py:25] Trying to hack submission 250812313 ...
2024-03-11:23:55:49,377 ERROR    [stress.py:29] None
2024-03-11:23:55:49,378 ERROR    [stress.py:30] Traceback (most recent call last):
  File "/home/suman/codeforces-hack-companion/judge/executor.py", line 78, in exec
    process = subprocess.run(shell_cmds, capture_output=True, check=True, cwd=task.path, input=stdin, text=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['perl', '/home/suman/codeforces-hack-companion/judge/timeout.pl', '-t', '3', '-m', '262144', 'python3', '-c', 'import math\r\nimport random\r\nimport sys\r\nfrom bisect import bisect_left, bisect_right\r\nfrom collections import deque, Counter, defaultdict\r\nfrom functools import cmp_to_key, reduce\r\nfrom heapq import heappush, heappop\r\nfrom itertools import accumulate, product, permutations\r\nfrom operator import xor\r\nfrom typing import Iterable, Iterator, Generic, TypeVar, List, Union\r\n\r\nread_from_file, de, useDfs = 0, 0, 1\r\n\r\nif useDfs:\r\n    from types import GeneratorType\r\n\r\n\r\n    def bootstrap(f, stack=[]):\r\n        def wrappedfunc(*args, **kwargs):\r\n            if stack:\r\n                return f(*args, **kwargs)\r\n            else:\r\n                to = f(*args, **kwargs)\r\n                while True:\r\n                    if type(to) is GeneratorType:\r\n                        stack.append(to)\r\n                        to = next(to)\r\n                    else:\r\n                        stack.pop()\r\n                        if not stack:\r\n                            break\r\n                        to = stack[-1].send(to)\r\n                return to\r\n\r\n        return wrappedfunc\r\n\r\nif 1:\r\n    input = lambda: sys.stdin.readline().strip("\\r\\n")\r\n\r\n\r\n    def I():\r\n        return input()\r\n\r\n\r\n    def ii():\r\n        return int(input())\r\n\r\n\r\n    def li():\r\n        return list(input().split())\r\n\r\n\r\n    def mi():\r\n        return map(int, input().split())\r\n\r\n\r\n    def gmi():\r\n        return map(lambda x: int(x) - 1, input().split())\r\n\r\n\r\n    def lgmi():\r\n        return list(map(lambda x: int(x) - 1, input().split()))\r\n\r\n\r\n    def lii():\r\n        return list(map(int, input().split()))\r\n\r\nif read_from_file:\r\n    fin = open(\'std/input.txt\', \'r\')\r\n    input = lambda: fin.readline().strip()\r\n    output_file = open("std/output.txt", "w")\r\n\r\n\r\n    def fprint(*args, **kwargs):\r\n        print(*args, **kwargs, file=output_file)\r\n\r\n\r\n\r\nfor _ in range(ii()):\r\n    n,m,k = mi()\r\n    a = lii()\r\n    b = lii()\r\n    c = lii()\r\n    b.sort()\r\n    c.sort()\r\n    bb = []\r\n    cc = []\r\n    for i in range(m):\r\n        if i > 0 and b[i] == b[i - 1]:continue\r\n        bb.append(b[i])\r\n    b = bb\r\n    m = len(b)\r\n    for i in range(k):\r\n        if i > 0 and c[i] == c[i - 1]:continue\r\n        cc.append(c[i])\r\n    c = cc\r\n    k = len(c)\r\n    mx = max(a[i] - a[i - 1] for i in range(1,n))\r\n    mx2 = 0\r\n    cnt = 0\r\n    idx = 0\r\n    for i in range(1,n):\r\n        if a[i] - a[i - 1] == mx:\r\n            cnt += 1\r\n    if cnt > 1:\r\n        print(mx)\r\n    else:\r\n        mx = 0\r\n        for i in range(1, n):\r\n            if a[i] - a[i - 1] > mx:\r\n                mx2 = mx\r\n                idx = i\r\n                mx = a[i] - a[i - 1]\r\n            elif a[i] - a[i - 1] == mx:\r\n                mx2 = mx\r\n            elif a[i] - a[i - 1] > mx2:\r\n                mx2 = a[i] - a[i - 1]\r\n        idx -= 1\r\n        ans = mx\r\n        for i in range(m):\r\n            l = bisect_right(c,a[idx] - b[i])\r\n            r = bisect_left(c,a[idx + 1] - b[i]) - 1\r\n            if l > r or l >= k or r < 0:\r\n                continue\r\n            ll,rr = l,r\r\n            def f(o):\r\n                return abs(a[idx] + a[idx + 1] - 2 * (b[i] + c[o]))\r\n            while rr - ll > 4:\r\n                m1 = ll + (rr - ll) // 3\r\n                m2 = rr - (rr - ll) // 3\r\n                v1, v2 = f(m1), f(m2)\r\n                if v1 < v2:\r\n                    rr = m2\r\n                else:\r\n                    ll = m1\r\n            v, ca = f(ll), ll\r\n            for j in range(ll + 1, rr + 1):\r\n                vv = f(j)\r\n                if vv < v:\r\n                    v = vv\r\n                    ca = j\r\n            tmp = max(a[idx + 1]-(b[i] + c[ca]),b[i] + c[ca] - a[idx],mx2)\r\n            ans = min(ans,tmp)\r\n        print(ans)']' returned non-zero exit status 1.

2024-03-11:23:55:49,379 INFO     [fetch.py:72] Sleeping for 1 second
2024-03-11:23:55:50,381 INFO     [fetch.py:72] Sleeping for 1 second
2024-03-11:23:55:51,383 INFO     [fetch.py:81] Currently Fetching https://codeforces.com/contest/1941/submission/250812215 ...
2024-03-11:23:55:59,261 INFO     [hack.py:25] Trying to hack submission 250812215 ...
2024-03-11:23:56:01,331 INFO     [fetch.py:81] Currently Fetching https://codeforces.com/contest/1941/submission/250812154 ...
2024-03-11:23:56:08,393 INFO     [hack.py:25] Trying to hack submission 250812154 ...
2024-03-11:23:56:11,058 ERROR    [stress.py:29] None
2024-03-11:23:56:11,058 ERROR    [stress.py:30] Traceback (most recent call last):
  File "/home/suman/codeforces-hack-companion/judge/executor.py", line 78, in exec
    process = subprocess.run(shell_cmds, capture_output=True, check=True, cwd=task.path, input=stdin, text=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['perl', '/home/suman/codeforces-hack-companion/judge/timeout.pl', '-t', '3', '-m', '262144', '/tmp/250812154_exe']' returned non-zero exit status 134.

2024-03-11:23:56:11,059 INFO     [fetch.py:81] Currently Fetching https://codeforces.com/contest/1941/submission/250812085 ...
2024-03-11:23:56:17,535 INFO     [hack.py:25] Trying to hack submission 250812085 ...
2024-03-11:23:56:19,583 INFO     [fetch.py:81] Currently Fetching https://codeforces.com/contest/1941/submission/250811993 ...
2024-03-11:23:56:26,268 INFO     [hack.py:25] Trying to hack submission 250811993 ...
2024-03-11:23:56:28,892 ERROR    [stress.py:29] None
2024-03-11:23:56:28,893 ERROR    [stress.py:30] Traceback (most recent call last):
  File "/home/suman/codeforces-hack-companion/judge/executor.py", line 78, in exec
    process = subprocess.run(shell_cmds, capture_output=True, check=True, cwd=task.path, input=stdin, text=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['perl', '/home/suman/codeforces-hack-companion/judge/timeout.pl', '-t', '3', '-m', '262144', '/tmp/250811993_exe']' returned non-zero exit status 139.

2024-03-11:23:56:28,894 INFO     [fetch.py:81] Currently Fetching https://codeforces.com/contest/1941/submission/250811985 ...
2024-03-11:23:56:37,144 INFO     [hack.py:25] Trying to hack submission 250811985 ...
2024-03-11:23:56:39,188 INFO     [fetch.py:81] Currently Fetching https://codeforces.com/contest/1941/submission/250811972 ...
2024-03-11:23:56:44,414 INFO     [hack.py:25] Trying to hack submission 250811972 ...
2024-03-11:23:56:54,335 ERROR    [stress.py:29] None
2024-03-11:23:56:54,335 ERROR    [stress.py:30] Traceback (most recent call last):
  File "/home/suman/codeforces-hack-companion/judge/executor.py", line 78, in exec
    process = subprocess.run(shell_cmds, capture_output=True, check=True, cwd=task.path, input=stdin, text=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['perl', '/home/suman/codeforces-hack-companion/judge/timeout.pl', '-t', '3', '-m', '262144', '/tmp/250811972_exe']' returned non-zero exit status 134.

2024-03-11:23:56:54,336 INFO     [fetch.py:81] Currently Fetching https://codeforces.com/contest/1941/submission/250811951 ...
2024-03-11:23:57:00,801 INFO     [hack.py:25] Trying to hack submission 250811951 ...
2024-03-11:23:57:03,408 ERROR    [stress.py:29] None
2024-03-11:23:57:03,408 ERROR    [stress.py:30] Traceback (most recent call last):
  File "/home/suman/codeforces-hack-companion/judge/executor.py", line 78, in exec
    process = subprocess.run(shell_cmds, capture_output=True, check=True, cwd=task.path, input=stdin, text=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['perl', '/home/suman/codeforces-hack-companion/judge/timeout.pl', '-t', '3', '-m', '262144', '/tmp/250811951_exe']' returned non-zero exit status 139.

2024-03-11:23:57:03,409 INFO     [fetch.py:81] Currently Fetching https://codeforces.com/contest/1941/submission/250811938 ...
2024-03-11:23:57:10,213 INFO     [hack.py:25] Trying to hack submission 250811938 ...
2024-03-11:23:57:12,266 INFO     [fetch.py:81] Currently Fetching https://codeforces.com/contest/1941/submission/250811868 ...
